server:
  port: 7799

spring:
  application:
    name: hytrix
  jmx:
    default_domain: hystrix
    default-domain: hystrix
    enabled: false

endpoints:
  jmx:
    domain: hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
