server:
  port: 80

spring:
  application:
    name: consumer-feign
  main:
     web-environment: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
