server:
  port: 8761

spring:
  application:
    name: discovery
  jmx:
    enabled: false
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

